# Node.js 22.14.0 사용
FROM node:22.14.0

# 앱 작업 디렉토리 생성
WORKDIR /app

# 의존성 설치용 package.json, lock 파일 복사
COPY package*.json ./
RUN npm install

# 소스 복사
COPY . .

# 외부에 열 포트
EXPOSE 5000

# 서버 실행
CMD ["node", "server.js"]
